import styles from "./Posts.module.css";

const Posts = () => {
    return (
        <div className={styles.posts}>
            <div className={styles.post_item}>Post 1: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tristique mauris ligula, ut ultricies lacus ultricies sit amet. Sed gravida suscipit ornare. Phasellus dapibus gravida enim, id vestibulum dolor vulputate vitae. Suspendisse vel justo sit amet ante convallis pharetra at at ipsum. Duis hendrerit tincidunt risus, a pretium mauris molestie ac.</div>
            <div className={styles.post_item}>Post 2: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tristique mauris ligula, ut ultricies lacus ultricies sit amet. Sed gravida suscipit ornare. Phasellus dapibus gravida enim, id vestibulum dolor vulputate vitae. Suspendisse vel justo sit amet ante convallis pharetra at at ipsum. Duis hendrerit tincidunt risus, a pretium mauris molestie ac. Quisque facilisis dolor quis mi posuere, nec accumsan quam aliquam. Donec purus risus, ornare non felis et, pharetra gravida augue. Nam eu lectus sed nibh fermentum tempor. Sed eget tellus nulla. Sed orci sapien, bibendum non erat tincidunt, sagittis pulvinar ipsum. Aliquam erat volutpat. Pellentesque a arcu sed turpis cursus pharetra et sed odio. Aenean aliquam condimentum urna, vel tempus ipsum fringilla sit amet.

                Donec pretium mi velit, eu ullamcorper massa rutrum at. Integer sodales nunc eu ex rutrum, ac congue elit ullamcorper. Nulla vestibulum sem quis malesuada viverra. Etiam malesuada justo sem, id iaculis risus egestas convallis. Phasellus nulla massa, malesuada non quam ut, sagittis lobortis erat. Phasellus libero diam, commodo quis mi et, rhoncus malesuada neque. Duis dignissim lectus in ullamcorper porta. Donec sem nulla, feugiat eget ornare vitae, maximus nec enim. Maecenas eu ipsum erat. Donec in purus cursus, varius sapien iaculis, volutpat ex.

                Morbi fermentum, lorem at ornare ultrices, lorem nisl vehicula risus, a tristique augue tortor sit amet tellus. Maecenas turpis augue, rutrum ut erat id, viverra mattis purus. Etiam consequat urna a ex commodo luctus. Proin consequat tempus auctor. Donec pellentesque lectus ut mauris aliquet, non blandit nisl porta. Vestibulum erat neque, condimentum quis nunc at, tristique tincidunt lectus. Sed ac viverra ipsum. Etiam consequat, lacus a maximus pulvinar, dolor tortor posuere neque, id cursus erat justo eu ligula. Cras euismod luctus nisi, non ornare ligula congue vitae. Mauris ornare, metus a blandit tempor, leo quam blandit lectus, sollicitudin gravida leo tortor ac nunc. Ut nibh magna, auctor at dolor nec, lacinia volutpat augue. Vivamus in metus eros. Nullam malesuada velit ante. Duis id mi mollis, vulputate nibh nec, tristique lorem. Ut ante ligula, pharetra nec metus ornare, fermentum aliquet risus.

                Curabitur dapibus purus viverra lorem molestie fermentum. Cras pharetra a justo sed ornare. Maecenas elementum ligula in nisl malesuada, eget consectetur ante dignissim. Aliquam tincidunt vehicula facilisis. Aenean maximus faucibus lacus at fringilla. Proin quis sem vitae nisl varius condimentum. Vivamus feugiat tempus dolor facilisis consequat. Aliquam purus eros, bibendum et dui vitae, consequat venenatis tellus. Duis mollis aliquet mi ut placerat. Nulla facilisi. Maecenas non gravida ex. Integer ut mattis tellus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Quisque fringilla orci eget tellus commodo, sit amet suscipit quam dictum. Curabitur dolor tortor, feugiat eget metus et, imperdiet cursus nisi. Suspendisse sed magna velit.

                Praesent quis lacus nisl. Aliquam erat volutpat. Phasellus maximus turpis enim, vel dignissim orci posuere vitae. Proin urna turpis, pharetra in bibendum vel, auctor non ex. Duis interdum metus eget interdum fermentum. Cras ac arcu at sapien vestibulum eleifend. Nunc sed convallis odio, condimentum blandit orci. Nullam metus ex, facilisis eget dignissim quis, ultrices sit amet mi. Donec tempor pellentesque orci, nec gravida nulla venenatis commodo.</div>
            <div  className={styles.post_item}>Post 3</div>
        </div>
    );
};

export default Posts;